// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlTnf3qgpc5l3Av9LTMGHi4tHSfNRQv8',
    appId: '1:279309055875:android:3abb3ca69bc3751456e8b6',
    messagingSenderId: '279309055875',
    projectId: 'servicios-firestore-sa',
    storageBucket: 'servicios-firestore-sa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxWIRPRciFyvSsQNEUQr46C2xYmTx4-Y',
    appId: '1:279309055875:ios:c0623baaa9dbbbba56e8b6',
    messagingSenderId: '279309055875',
    projectId: 'servicios-firestore-sa',
    storageBucket: 'servicios-firestore-sa.appspot.com',
    androidClientId: '279309055875-5gir6gqrfdf0cjuq3aiitllgeq9kojig.apps.googleusercontent.com',
    iosClientId: '279309055875-eep1g6oi7qe2d4qru28ftpu8bvp98nod.apps.googleusercontent.com',
    iosBundleId: 'com.example.examen3',
  );
}
